owner: GetRSS
repo: upptime

sites:
  - name: RSSBox
    url: $RSSBOX
  - name: RSSHub
    url: $RSSHUB
  - name: RSS-Bridge
    url: $RSSBRIDGE
  - name: Reddit-RSS
    url: $REDDITRSS

status-website:
  theme: night
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RSS Feed Generator Status
  introTitle: "**Upptime** for RSS Feed Generator"
  introMessage: RSS 피드제작기 모니터
